
services:
#  chat-web:
#    image: apconw/chat-vue3-mvp:1.1.1
#    container_name: chat-vue3-mvp
#    ports:
#      - "8081:80"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    depends_on:
#      - chat-service

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - ./volume/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin12345678
    command: server /data --console-address ":9001"

#  chat-service:
#    image: apconw/sanic-web:1.1.1
#    container_name: sanic-web
#    environment:
#      - ENV=test
#      - DIFY_SERVER_URL=http://host.docker.internal:18000
#      - DIFY_DATABASE_QA_API_KEY=app-AXDUw8TtcY7N6TMGHkPaC4VF
#      - MINIO_ENDPOINT=host.docker.internal:19000
#      - MINIO_ACCESS_KEY=sIR5eeDkiwoo779yNJbw
#      - MiNIO_SECRET_KEY=MreuQ3aC1ymHJeo3QfzSg7aPz7PqlxeOw39nZUdE
#    ports:
#      - "8088:8088"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#
  mysql:
    image: mysql:latest
    container_name: chat-db
    ports:
      - "13007:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - CHARACTER_SET_SERVER=utf8mb4
      - COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - ./volume/mysql/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
